### ISSUE TITLE
Monkey Patch Xformers use `past_key_value` but `use_cache` can't be `True`?

### ISSUE THREAD

**Issue by fahadh4ilyas** [DachengLi1/LongChat#15]
I'm confused with this script [longchat/train/monkey_patch/llama_xformer_monkey_patch.py](https://github.com/DachengLi1/LongChat/blob/longeval/longchat/train/monkey_patch/llama_xformer_monkey_patch.py). I thought by not allowing `use_cache` parameter to `True` means `past_key_value` will not be used and not return. But, somehow `past_key_value` is still used but `attn_weights` is always `None`. Did you mean to set

```python
assert not output_attentions, "xformer does not support output_attentions=True"
```

instead of

```python
assert not use_cache, "xformer does not support use_cache=True"
```

**Comment by DachengLi1** [comment]
@fahadh4ilyas Sorry for the confusion. The codes are intended to be used with use_cache=False, output_attentions=False. We will clean the use_cache logic in the next refactoring. Thanks for letting us know!

**Comment by fahadh4ilyas** [comment]
So, `past_key_value` is not supported in xformers?

**Comment by DachengLi1** [comment]
Right, it is intended for Training purpose, where past_key_value is always not provided.

**Comment by fahadh4ilyas** [comment]
Okay, that makes sense. Which one is faster? Using flash attention or xformers?

**Comment by DachengLi1** [comment]
In my benchmark during experiments, they are the same. Xformer supports V100, but flash does not.

**Comment by fahadh4ilyas** [comment]
What about for inference? Doesn't inference need `past_key_value`? Does this mean xformers can't be used for inference?

**Comment by DachengLi1** [comment]
Yes, xformer and flash attention are not intended for inference in their most naive usage. We have more advanced [system](https://github.com/vllm-project/vllm) supporting this, and some models already been supported by this system in FastChat. LongChat is the next todo.

**Comment by fahadh4ilyas** [comment]
Okay right... Thank you for the answer...

**Comment by lucasjinreal** [comment]
@DachengLi1 Hi, so if one need support v100 training, it's better using xformers?

BTW, does it work if full params finetune with xformers or flashattn?
