### ISSUE TITLE
The purpose of pretrain script?

### ISSUE THREAD

**Issue by fahadh4ilyas** [DachengLi1/LongChat#17]
Doesn't LongChat is a fine-tune from Llama Model but with a tweak script to rotation embedding layer? Or you have to do pretraining first before fine-tuning with sharegpt data? Because the script for pretraining exists and makes me assume we have to pretrained Llama Model first before fine-tuning.

**Comment by DachengLi1** [comment]
@fahadh4ilyas Thanks for the question! The pre-training script was not used for LongChat. It is for people who wish to do some pre-training experiments.

**Comment by fahadh4ilyas** [comment]
Thank you for the clarification...
