### ISSUE TITLE
flash_attn installed, but got ImportErrorImportError

### ISSUE THREAD

**Issue by brewswang** [DachengLi1/LongChat#30]
ImportErrorImportError: : cannot import name 'flash_attn_unpadded_qkvpacked_func'

**Comment by DachengLi1** [comment]
@brewswang Please consider renaming the function based on flash-attn2, they changed the function names.

**Comment by brewswang** [comment]
thanks,

**Comment by brewswang** [comment]
These functions have been renamed:
- `flash_attn_unpadded_func` -> `flash_attn_varlen_func`
- `flash_attn_unpadded_qkvpacked_func` -> `flash_attn_varlen_qkvpacked_func`
- `flash_attn_unpadded_kvpacked_func` -> `flash_attn_varlen_kvpacked_func`

**Comment by brewswang** [comment]
希望对其他人有帮助
